name: Towing Log
options:
  bundleIdPrefix: com.shimondeitel.towinglog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Towing Log:
    type: application
    platform: iOS
    sources:
      - path: Towing Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.towinglog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Towing Log/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  Towing LogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Towing LogTests
      - path: Towing Log.storekit
    dependencies:
      - target: Towing Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.towinglog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  Towing LogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Towing LogUITests
    dependencies:
      - target: Towing Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.towinglog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Towing Log:
    build:
      targets:
        Towing Log: all
        Towing LogTests: [test]
        Towing LogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Towing Log.storekit
    test:
      config: Debug
      storeKitConfiguration: Towing Log.storekit
      targets:
        - Towing LogTests
        - Towing LogUITests
    archive:
      config: Release
